/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiAuditListItemDto } from '../models/api-audit-list-item-dto';
import { ApiPaginationMetadata } from '../models/api-pagination-metadata';
export interface ApiListAuditsResponse {
  items: Array<ApiAuditListItemDto>;
  metadata: ApiPaginationMetadata;
}
