/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiAuditListItemDto {
  area: string;
  auditId: string;
  author: string;
  endDate: string;
  score: number;
  startDate: string;
}
