/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiQuestionDto } from '../models/api-question-dto';
export interface ApiListQuestionsResponse {
  questions: Array<ApiQuestionDto>;
}
