/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * A custom implementation of Microsoft.AspNetCore.Mvc.ProblemDetails that utilizes the Microsoft.AspNetCore.Mvc.ProblemDetails.Extensions
 * property instead of defining custom properties. This ensures compatibility with
 * Microsoft.AspNetCore.Mvc.Infrastructure.DefaultApiProblemDetailsWriter,
 * which expects and includes the Microsoft.AspNetCore.Mvc.ProblemDetails.Extensions in the response.
 */
export interface ApiCustomValidationProblemDetails {
  detail?: string | null;
  errors: Array<string>;
  instance?: string | null;
  status?: number | null;
  title?: string | null;
  type?: string | null;

  [key: string]: Array<string> | any | number | null | string | null | undefined;
}
