/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiProblemDetails {
  detail?: string | null;
  instance?: string | null;
  status?: number | null;
  title?: string | null;
  type?: string | null;

  [key: string]: any | number | null | string | null | undefined;
}
