/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiAuditActionForCreationDto {
  auditActionId: string;
  auditId: string;
  description: string;
  isComplete: boolean;
}
