/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiUpdateAuditActionResponse {
  auditActionId: string;
  description: string;
  isComplete: boolean;
  lastVersion: number;
}
