/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiAnswerForCreationDto {
  answerId: string;
  answerText: string;
  answerType: string;
  questionId: string;
}
