/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiAnswerDto } from '../models/api-answer-dto';
import { ApiAuditActionDto } from '../models/api-audit-action-dto';
export interface ApiGetAuditResponse {
  actions: Array<ApiAuditActionDto>;
  answers: Array<ApiAnswerDto>;
  area: string;
  auditId: string;
  author: string;
  endDate: string;
  score: number;
  startDate: string;
}
