/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiAnswerDto } from './models/api-answer-dto';
export type { ApiAnswerForCreationDto } from './models/api-answer-for-creation-dto';
export type { ApiAuditActionDto } from './models/api-audit-action-dto';
export type { ApiAuditActionForCreationDto } from './models/api-audit-action-for-creation-dto';
export type { ApiAuditListItemDto } from './models/api-audit-list-item-dto';
export type { ApiCustomValidationProblemDetails } from './models/api-custom-validation-problem-details';
export type { ApiGetAuditResponse } from './models/api-get-audit-response';
export type { ApiListAuditsResponse } from './models/api-list-audits-response';
export type { ApiListQuestionsResponse } from './models/api-list-questions-response';
export type { ApiLoginRequest } from './models/api-login-request';
export type { ApiPaginationMetadata } from './models/api-pagination-metadata';
export type { ApiProblemDetails } from './models/api-problem-details';
export type { ApiQuestionDto } from './models/api-question-dto';
export type { ApiRegisterRequest } from './models/api-register-request';
export type { ApiSaveAuditActionRequest } from './models/api-save-audit-action-request';
export type { ApiSaveAuditActionResponse } from './models/api-save-audit-action-response';
export type { ApiSaveAuditRequest } from './models/api-save-audit-request';
export type { ApiSaveAuditResponse } from './models/api-save-audit-response';
export type { ApiUpdateAuditActionRequest } from './models/api-update-audit-action-request';
export type { ApiUpdateAuditActionResponse } from './models/api-update-audit-action-response';
export type { ApiUserDto } from './models/api-user-dto';
